---
- name: Manage files
  hosts: localhost            #for the appling thosand machine use all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Manage etc motd
    lineinfile:
      path: "/etc/motd"
      regexp: "^This machine is managed by SysEng"  #find this line in machine 
      line: "This machine is managed by DevOps"     #change with this line 


  - name: Block
    blockinfile:
      path: "/tmp/non_existent"
      block: |
        This file is created by me
        and managed by me
      create: yes