---                                                                 #THIS IS JUST FOR NOTE RUN THE OTHER ONE 
- name: My First playbook
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Setup  a repo                            #INSTALLATION-1 PART
    shell: rpm -Uvh http://repo.nagios.com/nagios/7/nagios-repo-7-4.el7.noarch.rpm

  - name: Install ncpa                             ##INSTALLATION-2 PART
    package: 
      name: ncpa                        #note:in company here you will use exact version like ncpa .2.3.48.rpm
      state: present

  - name: Change a line       #Lineinfile module> it will search "community_string" will replace "Str0ngT0k3n1"
    lineinfile:
      path: /usr/local/ncpa/etc/ncpa.cfg
      regexp: '^community_string'
      line: 'community_string = mytoken2020'     #Str0ngT0k3n1   #Note :the important thing is token
    notify: RESTART_NCPA

  handlers:        #if up everthing is successfull just restart.
    - name: RESTART_NCPA
      systemd:
        name: ncpa_listener
        state: restarted