---
- name: Create ec2-instance
  hosts: localhost
  become: true
  become_method: sudo
  gather_facts: False
  tasks:
    - name: Launch instance
       ec2:
        key_name: Bastion
        instance_type: t2.medium
        image: ami-01a6e31ac994bbc09
        wait: true
        region: eu-west-2 
        vpc_subnet_id: subnet-003488d302b440692
        assign_public_ip: yes
      register: ec2
