---
- name: My user input playbook
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name:

- name: user input
  hosts: all
  vars_prompt:
   name: var1
   prompt: "What is your username?"
  tasks:    
  - name: here is message
    debug:
     msg: 'You passed it {{ var1 }}'
