---
- name: Add the user 'bob'
  hosts: all
  become: true
  become_method: sudo
  tasks: 
  - name: Add Bob
    user:
      name: bob
      state: present
  - name: Create a 2048-bit SSH key for user Bob in ~bob/.ssh/id_rsa
    user:
      name: bob
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Add Ben
    user:
      name: ben
      state: present
  - name: Create a 2048-bit SSH key for user Bob in ~ben/.ssh/id_rsa
    user:
      name: ben
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa      

  - name: Add Lisa
    user:
      name: lisa
      state: present
  - name: Create a 2048-bit SSH key for user Bob in ~lisa/.ssh/id_rsa
    user:
      name: lisa
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Add Katty
    user:
      name: katty
      state: present
  - name: Create a 2048-bit SSH key for user Bob in ~katty/.ssh/id_rsa
    user:
      name: katty
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa