---
- name: My First Playbook
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Run find command
    shell: 'find   /var/log     -type f      -name "*.log"     -size   +100M    -exec   gzip -v9   {}      +'
